[package]
name = "zapocet"
version = "0.1.0"
authors = ["Daniel Rod <dsrod@seznam.cz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd.git" }